services:
  db:
    image: postgres
    restart: always
    container_name: postgres_db_todo_v2
    env_file:
      - .env
    ports:
      - '5438:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: todo_db_v2
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist database data

  adminer:
    image: adminer
    container_name: adminer_task_v2
    ports:
      - '8082:8080'
volumes:
  postgres-data: